name: build ukui RPM package

on: 
  workflow_dispatch:
    inputs:
      job:
        description: 'Which job will be running, build-on-fedora-33 or build-on-centos-8'     
        required: true
        default: 'build-on-centos-8'

jobs:
  build-on-fedora-33:
    name: Build on Fedora 33
    runs-on: ubuntu-20.04
    container: docker.io/library/fedora:33
    if: github.event.inputs.job == 'build-on-fedora-33'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dnf install -y make rpm-build dnf-plugins-core
      - name: Build package
        run: make build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rpm-packages
          path: '~/rpmbuild/**/*.rpm'
  build-on-centos-8:
    name: Build on centos 8
    runs-on: ubuntu-20.04
    container: docker.io/library/centos:8
    if: github.event.inputs.job == 'build-on-centos-8'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dnf install -y make rpm-build dnf-plugins-core
      - name: Build package
        run:  make build     
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rpm-packages
          path: '~/rpmbuild/**/*.rpm'
            
