name: build ukui RPM package

on: 
  workflow_dispatch:
    inputs:
      job:
        description: 'which job will be running, centos-8 or fedora-33'     
        required: true
        default: 'centos-8'

jobs:
  fedora-33:
    name: on Fedora 33
    runs-on: ubuntu-20.04
    container: docker.io/library/fedora:33
    if: github.event.inputs.job == 'fedora-33'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dnf install -y make rpm-build dnf-plugins-core
      - name: Build package
        run: make build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
           '~/rpmbuild/SRPMS/'
           '~/rpmbuild/RPMS/'
  centos-8:
    name: on centos 8
    runs-on: ubuntu-20.04
    container: docker.io/library/centos:8
    if: github.event.inputs.job == 'centos-8'
    steps:
      - name: Checkout  source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dnf install -y make rpm-build dnf-plugins-core
      - name: Build package
        run:  make build     
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
           '~/rpmbuild/SRPMS/'
           '~/rpmbuild/RPMS/'
            
